### ISSUE TITLE
predictSV have some error

### ISSUE THREAD

**Issue by yangfeizZZ** [XiaoTaoWang/EagleC#11]
when i run predictSV,i have some error.
My code: predictSV --hic-5k M1.mcool::/resolutions/5000 --hic-10k M1.mcool::/resolutions/10000 --hic-50k M1.mcool::/resolutions/50000 -O SK-N-AS -g hg38 --balance-type ICE --output-format NeoLoopFinder --prob-cutoff-5k 0.8 --prob-cutoff-10k 0.8 --prob-cutoff-50k 0.99999
My error:File "/home/marh/miniconda3/envs/EagleC/bin/predictSV-single-resolution", line 276, in <module>
    run()
  File "/home/marh/miniconda3/envs/EagleC/bin/predictSV-single-resolution", line 227, in run
    intra_expected_count = intraPredict(clr, cnn_models, chroms, cache_folder, seq_depth,
  File "eaglec/scoreUtils.pyx", line 1263, in eaglec.scoreUtils.intraPredict
  File "eaglec/scoreUtils.pyx", line 1022, in eaglec.scoreUtils._intra_global_core
  File "/home/marh/miniconda3/envs/EagleC/lib/python3.8/site-packages/eaglec/utilities.py", line 380, in check_gaps_and_decays
    gaps = load_gap(clr, ref_genome=ref, balance=balance)
  File "/home/marh/miniconda3/envs/EagleC/lib/python3.8/site-packages/eaglec/utilities.py", line 326, in load_gap
    if ref_gaps[chromlabel][ref_i]:
IndexError: index 24896 is out of bounds for axis 0 with size 24896
Traceback (most recent call last):
  File "/home/marh/miniconda3/envs/EagleC/bin/predictSV", line 176, in <module>
    run()
  File "/home/marh/miniconda3/envs/EagleC/bin/predictSV", line 112, in run
    subprocess.check_call(' '.join(command), shell=True)
  File "/home/marh/miniconda3/envs/EagleC/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'predictSV-single-resolution -H M1.mcool::/resolutions/5000 --balance-type ICE -O SK-N-AS.CNN_SVs.5K.txt --genome hg38 --output-format full -C "#" "X" --prob-cutoff 0.8 --logFile SK-N-AS.log' returned non-zero exit status 1.
How to solve it,thanks you.

**Comment by XiaoTaoWang** [comment]
Hi, the error tells that your Hi-C reads were not mapped to the reference genome you specified in command (``-g hg38``). Can you double check the reference genome you used for mapping?

**Comment by yangfeizZZ** [comment]
> Hi, the error tells that your Hi-C reads were not mapped to the reference genome you specified in command (`-g hg38`). Can you double check the reference genome you used for mapping?

YES,when i change hg19,it irun successfully.
