### ISSUE TITLE
predictSV-ERROR: sequence item 2: expected str instance, NoneType found

### ISSUE THREAD

**Issue by X201231** [XiaoTaoWang/EagleC#15]
Hi, 

I got an error when I ran predictSV:

`predictSV --hic-50k ./mcools/qpca0322082203.mcool::/resolutions/50000 -O EagleC_output -g hg19 --balance-type Raw --output-format full --prob-cutoff-50k 0.95`

```
root                      INFO    @ 11/29/22 10:56:41: 
# ARGUMENT LIST:
# Cool URI at 5kb = None
# Cool URI at 10kb = None
# Cool URI at 50kb = ./mcools/qpca0322082203.mcool::/resolutions/50000
# Balance Type = Raw
# Reference Genome = hg19
# Included Chromosomes = ['#', 'X']
# Probability Cutoff for 5kb SVs = 0.8
# Probability Cutoff for 10kb SVs = 0.8
# Probability Cutoff for 50kb SVs = 0.95
# Output File Prefix = EagleC_output
# Output Format = full
# Log file name = EagleC_output.log
root                      INFO    @ 11/29/22 10:56:41: Predict SVs at 5kb resolution ...
Traceback (most recent call last):
  File "/share/home/hxie/miniconda3/envs/EagleC/bin/predictSV", line 176, in <module>
    run()
  File "/share/home/hxie/miniconda3/envs/EagleC/bin/predictSV", line 112, in run
    subprocess.check_call(' '.join(command), shell=True)
TypeError: sequence item 2: expected str instance, NoneType found
```

Thanks for your help!

**Comment by XiaoTaoWang** [comment]
Hi, the parameters ``--hic-5k`` and ``--hic-10k`` cannot be empty. To predict SVs at 50kb resolution only, you may want to use ``predictSV-single-resolution`` instead.

**Comment by X201231** [comment]
> Hi, the parameters `--hic-5k` and `--hic-10k` cannot be empty. To predict SVs at 50kb resolution only, you may want to use `predictSV-single-resolution` instead.

I will try it, thank you so much!
